🌍 Global Seismic Trends: Data-Driven Earthquake Insights Project
Python , Pandas, SQL , StreamLit Dashboard by Jamuna

In [4]:
!pip install requests

Requirement already satisfied: requests in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (2.32.5)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests) (2026.1.4)

In [5]:
!pip install pandas

Collecting pandas
  Using cached pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Using cached pandas-3.0.0-cp312-cp312-win_amd64.whl (9.7 MB)
Downloading numpy-2.4.1-cp312-cp312-win_amd64.whl (12.3 MB)
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
    --------------------------------------- 0.3/12.3 MB ? eta -:--:--
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   - -------------------------------------- 0.5/12.3 MB 60.6 kB/s eta 0:03:15
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   -- ------------------------------------- 0.8/12.3 MB 72.0 kB/s eta 0:02:41
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   --- ------------------------------------ 1.0/12.3 MB 87.7 kB/s eta 0:02:09
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ---- ----------------------------------- 1.3/12.3 MB 84.1 kB/s eta 0:02:11
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.6/12.3 MB 82.6 kB/s eta 0:02:10
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ----- ---------------------------------- 1.8/12.3 MB 87.2 kB/s eta 0:02:01
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------ --------------------------------- 2.1/12.3 MB 89.9 kB/s eta 0:01:54
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   ------- -------------------------------- 2.4/12.3 MB 92.0 kB/s eta 0:01:49
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   -------- ------------------------------- 2.6/12.3 MB 85.5 kB/s eta 0:01:54
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   --------- ------------------------------ 2.9/12.3 MB 88.6 kB/s eta 0:01:47
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ---------- ----------------------------- 3.1/12.3 MB 87.1 kB/s eta 0:01:46
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.4/12.3 MB 82.1 kB/s eta 0:01:49
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ----------- ---------------------------- 3.7/12.3 MB 88.2 kB/s eta 0:01:38
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------ --------------------------- 3.9/12.3 MB 90.6 kB/s eta 0:01:33
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   ------------- -------------------------- 4.2/12.3 MB 95.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25
   -------------- ------------------------- 4.5/12.3 MB 93.5 kB/s eta 0:01:25

In [6]:
!pip install datetime

Collecting datetime
  Using cached datetime-6.0-py3-none-any.whl.metadata (34 kB)
Collecting zope.interface (from datetime)
  Using cached zope_interface-8.2-cp312-cp312-win_amd64.whl.metadata (46 kB)
Collecting pytz (from datetime)
  Using cached pytz-2025.2-py2.py3-none-any.whl.metadata (22 kB)
Using cached datetime-6.0-py3-none-any.whl (52 kB)
Using cached pytz-2025.2-py2.py3-none-any.whl (509 kB)
Using cached zope_interface-8.2-cp312-cp312-win_amd64.whl (212 kB)
Installing collected packages: pytz, zope.interface, datetime

   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ---------------------------------------- 0/3 [pytz]
   ------------- -------------------------- 1/3 [zope.interface]
   ------------- -------------------------- 1/3 [zope.interface]
   ------------- -------------------------- 1/3 [zope.interface]
   ------------- -------------------------- 1/3 [zope.interface]
   -------------------------- ------------- 2/3 [datetime]
   ---------------------------------------- 3/3 [datetime]

Successfully installed datetime-6.0 pytz-2025.2 zope.interface-8.2

In [7]:
!pip install numpy

Requirement already satisfied: numpy in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (2.4.1)

In [8]:
!pip install plotly.express

Collecting pandas
  Using cached pandas-3.0.0-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting numpy>=1.26.0 (from pandas)
  Using cached numpy-2.4.1-cp312-cp312-win_amd64.whl.metadata (6.6 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas) (2.9.0.post0)
Collecting tzdata (from pandas)
  Using cached tzdata-2025.3-py2.py3-none-any.whl.metadata (1.4 kB)
Requirement already satisfied: six>=1.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Downloading pandas-3.0.0-cp312-cp312-win_amd64.whl (9.7 MB)
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.7 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   -- ------------------------------------- 0.5/9.7 MB 58.4 kB/s eta 0:02:38
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   --- ------------------------------------ 0.8/9.7 MB 27.9 kB/s eta 0:05:21
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ---- ----------------------------------- 1.0/9.7 MB 19.2 kB/s eta 0:07:34
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ----- ---------------------------------- 1.3/9.7 MB 28.0 kB/s eta 0:05:01
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------ --------------------------------- 1.6/9.7 MB 38.0 kB/s eta 0:03:35
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   ------- -------------------------------- 1.8/9.7 MB 47.0 kB/s eta 0:02:49
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38
   -------- ------------------------------- 2.1/9.7 MB 48.5 kB/s eta 0:02:38

WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000248C8BB2120>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/64/2d/4f8a2f192ed12c90a0aab47f5557ece0e56b0370c49de9454a09de7381b2/pandas-3.0.0-cp312-cp312-win_amd64.whl

^C

In [10]:
!pip install plotly

Collecting plotly
  Using cached plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Collecting narwhals>=1.15.1 (from plotly)
  Using cached narwhals-2.15.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly) (26.0)
Using cached plotly-6.5.2-py3-none-any.whl (9.9 MB)
Using cached narwhals-2.15.0-py3-none-any.whl (432 kB)
Installing collected packages: narwhals, plotly

   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   ---------------------------------------- 0/2 [narwhals]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   -------------------- ------------------- 1/2 [plotly]
   ---------------------------------------- 2/2 [plotly]

Successfully installed narwhals-2.15.0 plotly-6.5.2

Collecting plotly.express
  Using cached plotly_express-0.4.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=0.20.0 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly.express) (3.0.0)
Collecting plotly>=4.1.0 (from plotly.express)
  Downloading plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Collecting statsmodels>=0.9.0 (from plotly.express)
  Downloading statsmodels-0.14.6-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting scipy>=0.18 (from plotly.express)
  Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting patsy>=0.5 (from plotly.express)
  Downloading patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: numpy>=1.11 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly.express) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas>=0.20.0->plotly.express) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas>=0.20.0->plotly.express) (2025.3)
Collecting narwhals>=1.15.1 (from plotly>=4.1.0->plotly.express)
  Downloading narwhals-2.15.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly>=4.1.0->plotly.express) (26.0)
Requirement already satisfied: six>=1.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly.express) (1.17.0)
Using cached plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Downloading patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Downloading plotly-6.5.2-py3-none-any.whl (9.9 MB)
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   ---------------------------------------- 0.0/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   - -------------------------------------- 0.3/9.9 MB ? eta -:--:--
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19
   -- ------------------------------------- 0.5/9.9 MB 24.7 kB/s eta 0:06:19

WARNING: Attempting to resume incomplete download (9.5 MB/36.3 MB, attempt 1)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06B8B6630>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06C151EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF7DFA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF7FE30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF7C0B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Attempting to resume incomplete download (9.5 MB/36.3 MB, attempt 2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF86030>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF859D0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF84FB0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Attempting to resume incomplete download (12.3 MB/36.3 MB, attempt 3)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF843E0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06C151EE0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF7DFA0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF867B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF86150>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Attempting to resume incomplete download (12.3 MB/36.3 MB, attempt 4)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF86210>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF86BD0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF870B0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x000001A06BF87320>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl

Collecting plotly.express
  Using cached plotly_express-0.4.1-py2.py3-none-any.whl.metadata (1.7 kB)
Requirement already satisfied: pandas>=0.20.0 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly.express) (3.0.0)
Collecting plotly>=4.1.0 (from plotly.express)
  Using cached plotly-6.5.2-py3-none-any.whl.metadata (8.5 kB)
Collecting statsmodels>=0.9.0 (from plotly.express)
  Using cached statsmodels-0.14.6-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting scipy>=0.18 (from plotly.express)
  Using cached scipy-1.17.0-cp312-cp312-win_amd64.whl.metadata (60 kB)
Collecting patsy>=0.5 (from plotly.express)
  Using cached patsy-1.0.2-py2.py3-none-any.whl.metadata (3.6 kB)
Requirement already satisfied: numpy>=1.11 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly.express) (2.4.1)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas>=0.20.0->plotly.express) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas>=0.20.0->plotly.express) (2025.3)
Collecting narwhals>=1.15.1 (from plotly>=4.1.0->plotly.express)
  Using cached narwhals-2.15.0-py3-none-any.whl.metadata (13 kB)
Requirement already satisfied: packaging in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from plotly>=4.1.0->plotly.express) (26.0)
Requirement already satisfied: six>=1.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas>=0.20.0->plotly.express) (1.17.0)
Using cached plotly_express-0.4.1-py2.py3-none-any.whl (2.9 kB)
Using cached patsy-1.0.2-py2.py3-none-any.whl (233 kB)
Using cached plotly-6.5.2-py3-none-any.whl (9.9 MB)
Using cached narwhals-2.15.0-py3-none-any.whl (432 kB)
Downloading scipy-1.17.0-cp312-cp312-win_amd64.whl (36.3 MB)
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.0/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
   ---------------------------------------- 0.3/36.3 MB ? eta -:--:--
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.5/36.3 MB 87.4 kB/s eta 0:06:50
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
    --------------------------------------- 0.8/36.3 MB 117.7 kB/s eta 0:05:02
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.0/36.3 MB 114.4 kB/s eta 0:05:09
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.3/36.3 MB 122.0 kB/s eta 0:04:47
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   - -------------------------------------- 1.6/36.3 MB 116.3 kB/s eta 0:04:59
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 1.8/36.3 MB 106.4 kB/s eta 0:05:25
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.1/36.3 MB 110.1 kB/s eta 0:05:12
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.4/36.3 MB 111.6 kB/s eta 0:05:05
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   -- ------------------------------------- 2.6/36.3 MB 111.4 kB/s eta 0:05:03
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 2.9/36.3 MB 87.6 kB/s eta 0:06:22
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.1/36.3 MB 88.8 kB/s eta 0:06:14
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   --- ------------------------------------ 3.4/36.3 MB 82.3 kB/s eta 0:06:41
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.7/36.3 MB 69.0 kB/s eta 0:07:54
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 3.9/36.3 MB 70.9 kB/s eta 0:07:37
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31
   ---- ----------------------------------- 4.2/36.3 MB 71.3 kB/s eta 0:07:31

WARNING: Connection timed out while downloading.
WARNING: Attempting to resume incomplete download (32.2 MB/36.3 MB, attempt 1)
WARNING: Attempting to resume incomplete download (32.5 MB/36.3 MB, attempt 2)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000233B7C9C5F0>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl
WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0x00000233B7923B30>: Failed to establish a new connection: [Errno 11001] getaddrinfo failed')': /packages/92/ce/672ed546f96d5d41ae78c4b9b02006cedd0b3d6f2bf5bb76ea455c320c28/scipy-1.17.0-cp312-cp312-win_amd64.whl

In [11]:

import requests
import pandas as pd
from datetime import datetime, timedelta
import numpy as np
import plotly.express as px

In [20]:


from datetime import datetime, timezone,timedelta
end_date = datetime.now(timezone.utc)
start_date = end_date - timedelta(days=5 * 365)

start_str = start_date.strftime("%Y-%m-%d")
end_str = end_date.strftime("%Y-%m-%d")

In [17]:

url = "https://earthquake.usgs.gov/fdsnws/event/1/query"
limit = 20000
offset = 1

all_records = []

while True:
    params = {
        "format": "geojson",
        "starttime": start_str,
        "endtime": end_str,
        "minmagnitude": 3,
        "limit": limit,
        "offset": offset
    }

    print(f"Fetching batch starting at offset {offset} ...")
    response = requests.get(url, params=params)
    data = response.json()

    features = data.get("features", [])
    if not features:
        break  # no more data

    all_records.extend(features)
    offset += limit  # next batch

print(f"Total Earthquakes Loaded: {len(all_records)}")

Fetching batch starting at offset 1 ...
Fetching batch starting at offset 20001 ...
Fetching batch starting at offset 40001 ...
Fetching batch starting at offset 60001 ...
Fetching batch starting at offset 80001 ...
Fetching batch starting at offset 100001 ...
Fetching batch starting at offset 120001 ...
Total Earthquakes Loaded: 103660

In [18]:

df = pd.DataFrame(all_records) # Creating DataFrame for all features

In [19]:
df.head()

,type,properties,geometry,id
0,Feature,"{'mag': 5, 'place': 'Volcano Islands, Japan re...","{'type': 'Point', 'coordinates': [143.429, 23....",us7000rs0p
1,Feature,"{'mag': 4.6, 'place': '16 km NNE of Honoria, P...","{'type': 'Point', 'coordinates': [-74.6666, -8...",us7000rs0i
2,Feature,"{'mag': 3.8, 'place': '77 km S of Point Hope, ...","{'type': 'Point', 'coordinates': [-166.622, 67...",ak2026btoyfc
3,Feature,"{'mag': 4.5, 'place': '41 km WNW of Illapel, C...","{'type': 'Point', 'coordinates': [-71.5445, -3...",us7000rs08
4,Feature,"{'mag': 4.1, 'place': '4 km S of Epitálio, Gre...","{'type': 'Point', 'coordinates': [21.4946, 37....",us7000rs01

In [21]:
records = []                      # creating new DataFrame and assigning each features as columns

for eq in all_records:
    prop = eq["properties"]
    geom = eq["geometry"]["coordinates"]  # [longitude, latitude, depth]

    records.append({
        "id": eq["id"],
        "place": prop["place"],
        "mag": prop["mag"],
        "time": datetime.fromtimestamp(prop["time"] / 1000, tz=timezone.utc),
        "updated": datetime.fromtimestamp(prop["updated"] / 1000, tz=timezone.utc),
        "tz": prop["tz"],
        "felt": prop["felt"],
        "cdi": prop["cdi"],
        "mmi": prop["mmi"],
        "alert": prop["alert"],
        "status": prop["status"],
        "tsunami": prop["tsunami"],
        "sig": prop["sig"],
        "net": prop["net"],
        "code": prop["code"],
        "ids": prop["ids"],
        "sources": prop["sources"],
        "types": prop["types"],
        "nst": prop["nst"],
        "dmin": prop["dmin"],
        "rms": prop["rms"],
        "gap": prop["gap"],
        "magType": prop["magType"],
        "longitude": geom[0],
        "latitude": geom[1],
        "depth_km": geom[2],
        "title":prop["title"],
        "type":prop["type"],
        "locationSource": prop.get("locationSource"),
        "magSource": prop.get("magSource"),
        "depthError": prop.get("depthError"),
        "magNst": prop.get("magNst"),
        "magError": prop.get("magError"),
        "horizontalError": prop.get("horizontalError"),
    })

df = pd.DataFrame(records)

In [22]:
df.head()

,id,place,mag,time,updated,tz,felt,cdi,mmi,alert,...,latitude,depth_km,title,type,locationSource,magSource,depthError,magNst,magError,horizontalError
0,us7000rs0p,"Volcano Islands, Japan region",5.0,2026-01-25 22:02:10.618000+00:00,2026-01-26 01:55:14.040000+00:00,None,NaN,NaN,NaN,NaN,...,23.3940,10.000,"M 5.0 - Volcano Islands, Japan region",earthquake,None,None,None,None,None,None
1,us7000rs0i,"16 km NNE of Honoria, Peru",4.6,2026-01-25 20:29:01.866000+00:00,2026-01-25 20:46:45.040000+00:00,None,NaN,NaN,NaN,NaN,...,-8.6248,122.560,"M 4.6 - 16 km NNE of Honoria, Peru",earthquake,None,None,None,None,None,None
2,ak2026btoyfc,"77 km S of Point Hope, Alaska",3.8,2026-01-25 19:51:55.287000+00:00,2026-01-25 20:23:58.827000+00:00,None,NaN,NaN,2.014,NaN,...,67.6520,5.500,"M 3.8 - 77 km S of Point Hope, Alaska",earthquake,None,None,None,None,None,None
3,us7000rs08,"41 km WNW of Illapel, Chile",4.5,2026-01-25 19:24:40.117000+00:00,2026-01-25 19:40:39.040000+00:00,None,NaN,NaN,NaN,NaN,...,-31.4355,41.926,"M 4.5 - 41 km WNW of Illapel, Chile",earthquake,None,None,None,None,None,None
4,us7000rs01,"4 km S of Epitálio, Greece",4.1,2026-01-25 17:56:53.285000+00:00,2026-01-25 18:18:13.040000+00:00,None,NaN,NaN,NaN,NaN,...,37.5901,36.351,"M 4.1 - 4 km S of Epitálio, Greece",earthquake,None,None,None,None,None,None

In [23]:
df.to_csv("usgs_earthquakes_5yrs.csv", index=False)
print("Saved CSV successfully!")

Saved CSV successfully!

In [24]:
df.info() # checking it column values and its datatype

<class 'pandas.DataFrame'>
RangeIndex: 103660 entries, 0 to 103659
Data columns (total 34 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   id               103660 non-null  str
 1   place            103646 non-null  str
 2   mag              103660 non-null  float64
 3   time             103660 non-null  datetime64[us, UTC]
 4   updated          103660 non-null  datetime64[us, UTC]
 5   tz               0 non-null       object
 6   felt             16121 non-null   float64
 7   cdi              16121 non-null   float64
 8   mmi              8581 non-null    float64
 9   alert            4251 non-null    str
 10  status           103660 non-null  str
 11  tsunami          103660 non-null  int64
 12  sig              103660 non-null  int64
 13  net              103660 non-null  str
 14  code             103660 non-null  str
 15  ids              103660 non-null  str
 16  sources          103660 non-null  str
 17  types            103660 non-null  str
 18  nst              77093 non-null   float64
 19  dmin             99725 non-null   float64
 20  rms              103643 non-null  float64
 21  gap              100675 non-null  float64
 22  magType          103660 non-null  str
 23  longitude        103660 non-null  float64
 24  latitude         103660 non-null  float64
 25  depth_km         103660 non-null  float64
 26  title            103660 non-null  str
 27  type             103660 non-null  str
 28  locationSource   0 non-null       object
 29  magSource        0 non-null       object
 30  depthError       0 non-null       object
 31  magNst           0 non-null       object
 32  magError         0 non-null       object
 33  horizontalError  0 non-null       object
dtypes: datetime64[us, UTC](2), float64(11), int64(2), object(7), str(12)
memory usage: 26.9+ MB

In [25]:
reorder_columns = [
    "id","time","updated","latitude","longitude","depth_km","mag","magType","place","status",
    "tsunami","sig","net","nst","dmin","rms","gap","magError","depthError","magNst","locationSource",
    "magSource","types","ids","sources","type","tz","felt","cdi","mmi","alert","code","title"
]

# Reorder DataFrame
df = df[reorder_columns]

In [26]:

df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,ids,sources,type,tz,felt,cdi,mmi,alert,code,title
0,us7000rs0p,2026-01-25 22:02:10.618000+00:00,2026-01-26 01:55:14.040000+00:00,23.3940,143.4290,10.000,5.0,mb,"Volcano Islands, Japan region",reviewed,...,",us7000rs0p,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs0p,"M 5.0 - Volcano Islands, Japan region"
1,us7000rs0i,2026-01-25 20:29:01.866000+00:00,2026-01-25 20:46:45.040000+00:00,-8.6248,-74.6666,122.560,4.6,mb,"16 km NNE of Honoria, Peru",reviewed,...,",us7000rs0i,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs0i,"M 4.6 - 16 km NNE of Honoria, Peru"
2,ak2026btoyfc,2026-01-25 19:51:55.287000+00:00,2026-01-25 20:23:58.827000+00:00,67.6520,-166.6220,5.500,3.8,ml,"77 km S of Point Hope, Alaska",reviewed,...,",us7000rs0e,ak2026btoyfc,",",us,ak,",earthquake,None,NaN,NaN,2.014,NaN,2026btoyfc,"M 3.8 - 77 km S of Point Hope, Alaska"
3,us7000rs08,2026-01-25 19:24:40.117000+00:00,2026-01-25 19:40:39.040000+00:00,-31.4355,-71.5445,41.926,4.5,mwr,"41 km WNW of Illapel, Chile",reviewed,...,",us7000rs08,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs08,"M 4.5 - 41 km WNW of Illapel, Chile"
4,us7000rs01,2026-01-25 17:56:53.285000+00:00,2026-01-25 18:18:13.040000+00:00,37.5901,21.4946,36.351,4.1,mb,"4 km S of Epitálio, Greece",reviewed,...,",us7000rs01,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs01,"M 4.1 - 4 km S of Epitálio, Greece"

In [27]:
string_cols = ['magType','status','type','net','sources','types']

# Strip whitespace
for col in string_cols:
    df[col] = df[col].str.strip()

# Standardize case
df['magType'] = df['magType'].str.upper()
df['status']  = df['status'].str.lower()
df['type']    = df['type'].str.lower()
df['net']     = df['net'].str.upper()

# Replace empty strings with NaN
df[string_cols] = df[string_cols].replace('', pd.NA)

# normalizing magType values
valid_magtypes = {'ml':'ML','mw':'MW','mb':'MB','ms':'MS'}
df['magType'] = df['magType'].str.lower().map(valid_magtypes).fillna(df['magType'])

In [28]:
df.head()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,ids,sources,type,tz,felt,cdi,mmi,alert,code,title
0,us7000rs0p,2026-01-25 22:02:10.618000+00:00,2026-01-26 01:55:14.040000+00:00,23.3940,143.4290,10.000,5.0,MB,"Volcano Islands, Japan region",reviewed,...,",us7000rs0p,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs0p,"M 5.0 - Volcano Islands, Japan region"
1,us7000rs0i,2026-01-25 20:29:01.866000+00:00,2026-01-25 20:46:45.040000+00:00,-8.6248,-74.6666,122.560,4.6,MB,"16 km NNE of Honoria, Peru",reviewed,...,",us7000rs0i,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs0i,"M 4.6 - 16 km NNE of Honoria, Peru"
2,ak2026btoyfc,2026-01-25 19:51:55.287000+00:00,2026-01-25 20:23:58.827000+00:00,67.6520,-166.6220,5.500,3.8,ML,"77 km S of Point Hope, Alaska",reviewed,...,",us7000rs0e,ak2026btoyfc,",",us,ak,",earthquake,None,NaN,NaN,2.014,NaN,2026btoyfc,"M 3.8 - 77 km S of Point Hope, Alaska"
3,us7000rs08,2026-01-25 19:24:40.117000+00:00,2026-01-25 19:40:39.040000+00:00,-31.4355,-71.5445,41.926,4.5,MWR,"41 km WNW of Illapel, Chile",reviewed,...,",us7000rs08,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs08,"M 4.5 - 41 km WNW of Illapel, Chile"
4,us7000rs01,2026-01-25 17:56:53.285000+00:00,2026-01-25 18:18:13.040000+00:00,37.5901,21.4946,36.351,4.1,MB,"4 km S of Epitálio, Greece",reviewed,...,",us7000rs01,",",us,",earthquake,None,NaN,NaN,NaN,NaN,7000rs01,"M 4.1 - 4 km S of Epitálio, Greece"

In [29]:
df['time'] = pd.to_datetime(df['time'], errors='coerce')
df['year'] = df['time'].dt.year       #Year
df['month'] = df['time'].dt.month     #month
df['day'] = df['time'].dt.day         #day
df['day_of_week'] = df['time'].dt.day_name() #day_of_week

In [30]:

if 'depth_km' in df.columns:
    df['depth_flag'] = df['depth_km'].apply(lambda x: 'Shallow' if x <= 70 else 'Deep') # depth_flag like shallow or deep

if 'mag' in df.columns:
    def mag_flag(mag):
        if mag >= 7: return 'Destructive' # based on magnitude value--> mag_flag is derived
        elif mag >= 5: return 'Strong'
        else: return 'Moderate/Minor'
    df['mag_flag'] = df['mag'].apply(mag_flag)

In [31]:
for col in ['nst','magNst','sig']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce').fillna(0)

# Continuous → filling with median
for col in ['mag','depth_km','rms','gap','magError','depthError','dmin']:
    if col in df.columns:
        df[col] = pd.to_numeric(df[col], errors='coerce')
        median_val = df[col].median()
        df[col] = df[col].fillna(median_val)

# Removing impossible depths where depth cannot be a negative value
if 'depth_km' in df.columns:
    df.loc[df['depth_km'] < 0, 'depth_km'] = np.nan

In [32]:
df.isnull().sum()

id                     0
time                   0
updated                0
latitude               0
longitude              0
depth_km             102
mag                    0
magType                0
place                 14
status                 0
tsunami                0
sig                    0
net                    0
nst                    0
dmin                   0
rms                    0
gap                    0
magError          103660
depthError        103660
magNst                 0
locationSource    103660
magSource         103660
types                  0
ids                    0
sources                0
type                   0
tz                103660
felt               87539
cdi                87539
mmi                95079
alert              99409
code                   0
title                  0
year                   0
month                  0
day                    0
day_of_week            0
depth_flag             0
mag_flag               0
dtype: int64

In [33]:

df = df[(df['latitude'].between(-90,90)) & (df['longitude'].between(-180,180))]

In [34]:
# Extract first part before comma
df['origin'] = df['place'].str.extract(r'^\s*([^,]+)')

# Extract second part after comma
df['country'] = df['place'].str.extract(r'^[^,]+,\s*(.+)$')

# Optional: strip whitespace
df['origin'] = df['origin'].str.strip()
df['country'] = df['country'].str.strip()

In [35]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 103660 entries, 0 to 103659
Data columns (total 41 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   id              103660 non-null  str
 1   time            103660 non-null  datetime64[us, UTC]
 2   updated         103660 non-null  datetime64[us, UTC]
 3   latitude        103660 non-null  float64
 4   longitude       103660 non-null  float64
 5   depth_km        103558 non-null  float64
 6   mag             103660 non-null  float64
 7   magType         103660 non-null  str
 8   place           103646 non-null  str
 9   status          103660 non-null  str
 10  tsunami         103660 non-null  int64
 11  sig             103660 non-null  int64
 12  net             103660 non-null  str
 13  nst             103660 non-null  float64
 14  dmin            103660 non-null  float64
 15  rms             103660 non-null  float64
 16  gap             103660 non-null  float64
 17  magError        0 non-null       float64
 18  depthError      0 non-null       float64
 19  magNst          103660 non-null  float64
 20  locationSource  0 non-null       object
 21  magSource       0 non-null       object
 22  types           103660 non-null  str
 23  ids             103660 non-null  str
 24  sources         103660 non-null  str
 25  type            103660 non-null  str
 26  tz              0 non-null       object
 27  felt            16121 non-null   float64
 28  cdi             16121 non-null   float64
 29  mmi             8581 non-null    float64
 30  alert           4251 non-null    str
 31  code            103660 non-null  str
 32  title           103660 non-null  str
 33  year            103660 non-null  int32
 34  month           103660 non-null  int32
 35  day             103660 non-null  int32
 36  day_of_week     103660 non-null  str
 37  depth_flag      103660 non-null  str
 38  mag_flag        103660 non-null  str
 39  origin          103646 non-null  str
 40  country         84118 non-null   str
dtypes: datetime64[us, UTC](2), float64(14), int32(3), int64(2), object(3), str(17)
memory usage: 31.2+ MB

In [36]:

df.year.unique()

array([2026, 2025, 2024, 2023, 2022, 2021], dtype=int32)

In [37]:

df.month.unique()

array([ 1, 12, 11, 10,  9,  8,  7,  6,  5,  4,  3,  2], dtype=int32)

In [38]:
df.day_of_week.nunique()

7

In [39]:

df.day.nunique()

31

In [40]:
df.country.unique()

<StringArray>
[                 'Japan region',                          'Peru',
                        'Alaska',                         'Chile',
                        'Greece',      'Aleutian Islands, Alaska',
            'Dominican Republic',                   'Puerto Rico',
                         'Texas',                        'Taiwan',
 ...
                       'Namibia', 'Ñuñoa, Santiago, Chile, Chile',
               'Portugal region',                 'United States',
                            'NV',                    'Mauritania',
                            'AK',                        'Jordan',
                        'Guinea',        'New Zealand Earthquake']
Length: 240, dtype: str

In [41]:

country_null = df.loc[df['country'].isnull(), ['origin', 'country']]

In [42]:

country_null

                            origin country
19                     Fiji region     NaN
20       south of the Fiji Islands     NaN
26      southeast of Easter Island     NaN
36       south of the Fiji Islands     NaN
39                     Fiji region     NaN
...                            ...     ...
103634    west of Macquarie Island     NaN
103638      South Shetland Islands     NaN
103641                 Fiji region     NaN
103645            Mid-Indian Ridge     NaN
103656      South Shetland Islands     NaN

[19542 rows x 2 columns]

In [43]:
# mapping: substring → country
country_map = {
    'Alaska': 'United States',
    'California': 'United States',
    'Nevada': 'United States',
    'Oklahoma': 'United States',
    'South Carolina': 'United States',
    'Texas': 'United States',
    'Puerto Rico': 'United States',
    'Virgin Islands': 'United States',
    'Guam': 'United States',
    'Dominican Republic': 'Dominican Republic',
    'Mexico': 'Mexico',
    'Guatemala': 'Guatemala',
    'Panama': 'Panama',
    'Costa Rica': 'Costa Rica',
    'Colombia': 'Colombia',
    'Peru': 'Peru',
    'Chile': 'Chile',
    'Argentina': 'Argentina',
    'Ecuador': 'Ecuador',
    'El Salvador': 'El Salvador',
    'Russia': 'Russia',
    'India': 'India',
    'China': 'China',
    'Turkey': 'Turkey',
    'Iran': 'Iran',
    'Afghanistan': 'Afghanistan',
    'Pakistan': 'Pakistan',
    'Tajikistan': 'Tajikistan',
    'Kyrgyzstan': 'Kyrgyzstan',
    'Libya': 'Libya',
    'Egypt': 'Egypt',
    'Greenland': 'Greenland',
    'Iceland': 'Iceland',
    'Norway': 'Norway',
    'Portugal': 'Portugal',
    'New Zealand': 'New Zealand',
    'Australia': 'Australia',
    'Taiwan': 'Taiwan',
    'Japan': 'Japan',
    'Fiji': 'Fiji',
    'Tonga': 'Tonga',
    'Vanuatu': 'Vanuatu',
    'Croatia': 'Croatia',
    'Nicaragua': 'Nicaragua',
    'South Sandwich Islands': 'United Kingdom',
    'Bouvet Island': 'Norway',
    'Ascension Island': 'United Kingdom'
}

In [44]:

def fill_countries_by_substring(df, country_map): # reusable function mapping country
    
    
    # Mask only rows where country is null
    mask = df['country'].isna()
    
    for substring, country in country_map.items():
        df.loc[
            mask & df['origin'].str.contains(substring, case=False, na=False),
            'country'
        ] = country

    return df

In [45]:
country_map.update({
    # Country-based regions
    'Palau': 'Palau',
    'Kuril Islands': 'Russia',
    'Macquarie Island': 'Australia',
    'Revilla Gigedo Islands': 'Mexico',

    # Oceanic / marine regions
    'Mona Passage': 'Atlantic Ocean',
    'Leeward Islands': 'Atlantic Ocean',
    'Banda Sea': 'Pacific Ocean',
    'Molucca Sea': 'Pacific Ocean',
    'Loyalty Islands': 'Pacific Ocean',
    'northwest of the Kuril Islands': 'Pacific Ocean',
    'east of the Kuril Islands': 'Pacific Ocean',
    'west of Macquarie Island': 'Southern Ocean',
    'south of Africa': 'Indian Ocean',
})

In [46]:
country_null = df.loc[df['country'].isnull(), ['origin', 'country']]

In [47]:
country_null.origin.unique()

<StringArray>
[                                 'Fiji region',
                    'south of the Fiji Islands',
                   'southeast of Easter Island',
                              'south of Panama',
                       'southeast Indian Ridge',
                   'central Mid-Atlantic Ridge',
                                    'Banda Sea',
                                'Kuril Islands',
                'South Sandwich Islands region',
                              'Carlsberg Ridge',
 ...
                                            nan,
          'Kyrgyzstan-Tajikistan border region',
               'Illinois-Indiana border region',
                 'Russia-Georgia border region',
                        'Crozet Islands region',
                                 'Labrador Sea',
 'Kyrgyzstan-Tajikistan-Xinjiang border region',
                   'Oregon-Idaho border region',
                               'southern Italy',
                                        'Egypt']
Length: 344, dtype: str

In [48]:
country_map.update({
    # --- Atlantic Ocean ---
    'Mid-Atlantic Ridge': 'Atlantic Ocean',
    'South Atlantic Ocean': 'Atlantic Ocean',
    'North Atlantic Ocean': 'Atlantic Ocean',
    'Ascension Island': 'Atlantic Ocean',
    'Azores Islands': 'Atlantic Ocean',
    'Scotia Sea': 'Atlantic Ocean',

    # --- Pacific Ocean ---
    'East Pacific Rise': 'Pacific Ocean',
    'West Chile Rise': 'Pacific Ocean',
    'Galapagos': 'Pacific Ocean',
    'Easter Island': 'Pacific Ocean',
    'Mariana': 'Pacific Ocean',
    'Fiji': 'Fiji',
    'Tonga': 'Tonga',
    'Samoa': 'Pacific Ocean',

    # --- Indian Ocean ---
    'Mid-Indian Ridge': 'Indian Ocean',
    'Indian Ocean': 'Indian Ocean',
    'Carlsberg Ridge': 'Indian Ocean',
    'Chagos Archipelago': 'Indian Ocean',
    'Owen Fracture Zone': 'Indian Ocean',

    # --- Arctic Ocean ---
    'Bering Strait': 'Arctic Ocean',
    'Beaufort Sea': 'Arctic Ocean',
    'Greenland Sea': 'Greenland',
    'Norwegian Sea': 'Arctic Ocean',
    'Barents Sea': 'Arctic Ocean',

    # --- Southern Ocean ---
    'Bouvet Island': 'Norway',        # overrides earlier Bouvet→Norway mapping
    'South Sandwich Islands': 'Southern Ocean',
    'South Shetland Islands': 'Southern Ocean',
    'Balleny Islands': 'Southern Ocean',
    'Pacific-Antarctic Ridge': 'Southern Ocean',
})

In [49]:
country_null.to_csv("country_null.csv",index=False)

In [50]:
country_map.update({
    # Well-defined oceans
    'North Pacific Ocean': 'Pacific Ocean',
    'South Pacific Ocean': 'Pacific Ocean',
    'east central Pacific Ocean': 'Pacific Ocean',
    'southeast central Pacific Ocean': 'Pacific Ocean',
    'southern Pacific Ocean': 'Pacific Ocean',

    'Arctic Ocean': 'Arctic Ocean',
    'Bering Sea': 'Arctic Ocean',
    'Beaufort Sea': 'Arctic Ocean',
    'Laptev Sea': 'Arctic Ocean',
    'Greenland Sea': 'Arctic Ocean',

    'Indian Ocean': 'Indian Ocean',
    'Bay of Bengal': 'Indian Ocean',
    'Flores Sea': 'Indian Ocean',
    'Mozambique Channel': 'Indian Ocean',
    'Gulf of Aden': 'Indian Ocean',

    'South Atlantic Ocean': 'Atlantic Ocean',
    'southwestern Atlantic Ocean': 'Atlantic Ocean',
    'Drake Passage': 'Atlantic Ocean',
    'Davis Strait': 'Atlantic Ocean',
    'Labrador Sea': 'Atlantic Ocean',
    'Bay of Campeche': 'Atlantic Ocean',

    'Southern Ocean': 'Southern Ocean',
    'southwest of Africa': 'Southern Ocean',
    'Balleny Islands': 'Southern Ocean',
    'Kerguelen Islands region': 'Southern Ocean',

    # Countries (clear cases)
    'Burma': 'Myanmar',
    'Burma (Myanmar)': 'Myanmar',
    'Myanmar': 'Myanmar',
    'Eritrea': 'Eritrea',
    'Ethiopia': 'Ethiopia',
    'Romania': 'Romania',
    'Greece': 'Greece',
    'Nepal': 'Nepal',
    'Poland': 'Poland',
    'Kenya': 'Kenya',
    'South Africa': 'South Africa',
    'Tanzania': 'Tanzania',
    'Angola': 'Angola',
    'Morocco': 'Morocco',
    'Cuba region': 'Cuba',
    'Haiti region': 'Haiti',
    'Turkmenistan': 'Turkmenistan',
    'Kazakhstan-Uzbekistan border region': 'Kazakhstan/Uzbekistan',
    'Greece-Albania border region': 'Greece/Albania',

    # US regions
    'Eastern Montana': 'United States',
    'Colorado': 'United States',
    'Nebraska': 'United States',
    'Wyoming': 'United States',
    'Utah': 'United States',
    'New York': 'United States',
    'Hawaiian Islands region': 'United States',
    'Oregon-Idaho border region': 'United States',

    # Canada / Arctic
    'Baffin Bay': 'Canada/Greenland',
    'north of Svalbard': 'Norway (Svalbard Territory)',
    'Svalbard region': 'Norway (Svalbard Territory)',

    # Micronesia / Oceania
    'D\'Entrecasteaux Islands region': 'Papua New Guinea',
    'Federated States of Micronesia region': 'Micronesia',
    'Solomon Islands': 'Solomon Islands',
    'Santa Cruz Islands region': 'Solomon Islands',

    # Ambiguous / marine regions—must be treated as oceanic
    'Sea of Okhotsk': 'Pacific Ocean',
    'Celebes Sea': 'Pacific Ocean',
    'Bismarck Sea': 'Pacific Ocean',
    'Arafura Sea': 'Pacific Ocean',
    'Savu Sea': 'Indian Ocean',
    'Ionian Sea': 'Mediterranean Sea',
    'Aegean Sea': 'Mediterranean Sea',
    'Adriatic Sea': 'Mediterranean Sea',
    'Caspian Sea': 'Caspian Sea',  # landlocked
    'Ligurian Sea': 'Mediterranean Sea',
})

In [51]:
country_map.update({
    'Hubbard Glacier': 'United States',
    'Drake Passage': 'International Waters',
    'Solomon Islands': 'Solomon Islands',
    'South Pacific Ocean': 'International Waters',
    'Kuril Islands': 'Russia',
    'Fiji': 'Fiji',
    'New Zealand': 'New Zealand',
    'Indonesia': 'Indonesia',
    'Japan': 'Japan',
    'Philippines': 'Philippines',
    'Chile': 'Chile',
    'Mexico': 'Mexico',
    'Alaska': 'United States',
    'Puerto Rico': 'Puerto Rico',
    'U.S. Virgin Islands': 'U.S. Virgin Islands',
    'Russia': 'Russia',
    'India': 'India',
    'Turkmenistan': 'Turkmenistan',
    'Azores Islands': 'Portugal',
    'Kermadec Islands': 'New Zealand',
    'Tonga': 'Tonga',
    'Vanuatu': 'Vanuatu',
    'South Sandwich Islands': 'United Kingdom',
    'Mid-Atlantic Ridge': 'International Waters',
    'Mariana Islands': 'United States',
    'Caribbean Sea': 'International Waters',
    'Gulf of California': 'Mexico',
    'Banda Sea': 'Indonesia',
    'Samoa': 'Samoa',
    'Papua New Guinea': 'Papua New Guinea',
    'Nepal': 'Nepal',
    'Pakistan': 'Pakistan',
    'Iran': 'Iran',
    'Turkey': 'Turkey',
    'Greece': 'Greece',
    'Italy': 'Italy',
    'Hawaii': 'United States',
    'Vietnam':'Vietnam'
})

In [52]:
country_map.update({
    'Tristan da Cunha region': 'United Kingdom',
    'western Xizang': 'China',
    'Socotra region': 'Yemen',
    'Reykjanes Ridge': 'International Waters',
    'north of Severnaya Zemlya': 'Russia',
    'off the coast of Central America': 'International Waters',
    'off the coast of Oregon': 'United States',
    'Falkland Islands region': 'United Kingdom',
    'off the west coast of northern Sumatra': 'Indonesia',
    'south of Timor': 'Indonesia',
    'Azores-Cape St. Vincent Ridge': 'International Waters',
    'Mauritius - Reunion region': 'Mauritius/Reunion (France)',
    'east of the Philippine Islands': 'Philippines',
    'South Georgia Rise': 'International Waters',
    'east of Severnaya Zemlya': 'Russia',
    'north of Franz Josef Land': 'Russia',
    'Xizang-Qinghai border region': 'China',
    'Prince Edward Islands region': 'South Africa',
    'South Georgia Island region': 'United Kingdom',
    'west of Vancouver Island': 'Canada',
    'south of the Aleutian Islands': 'United States',
    'Southern Tibetan Plateau': 'China',
    'Tibetan Plateau': 'China',
    '2025 Southern Tibetan Plateau Earthquake': 'China',
    'off the coast of Washington': 'United States',
    'north of the New Siberian Islands': 'Russia',
    'Lomonosov Ridge': 'International Waters',
    'West of the Queen Charlotte Islands': 'Canada',
    'Santa Cruz Islands': 'Solomon Islands',
    'East Timor region': 'Timor-Leste',
    'Xinjiang-Xizang border region': 'China',
    'near the coast of Venezuela': 'Venezuela',
    'Cyprus region': 'Cyprus',
    'Honduras': 'Honduras',
    'Timor region': 'Timor-Leste',
    'Philippine Islands region': 'Philippines',
    'Bali Sea': 'Indonesia',
    'Bulgaria': 'Bulgaria',
    'Eastern Xizang': 'China',
    'Lake Almanor Earthquake': 'United States',
    'Trinidad': 'Trinidad and Tobago',
    'off the east coast of the United States': 'United States',
    'Jan Mayen Island region': 'Norway',
    'central Mediterranean Sea': 'International Waters',
    'Near the coast of Syria': 'Syria',
    'north of Honduras': 'Honduras',
    'Dead Sea region': 'Israel/Jordan',
    'Kahramanmaras Earthquake Sequence': 'Turkey',
    'Cape Verde': 'Cape Verde',
    'Kazakhstan-Xinjiang border region': 'China/Kazakhstan',
    'South Korea': 'South Korea',
    'western Uzbekistan': 'Uzbekistan',
    'Kashmir-Xinjiang border region': 'India/China',
    'Malta region': 'Malta',
    'northern Algeria': 'Algeria',
    'Democratic Republic of the Congo': 'DR Congo',
    'southern Idaho': 'United States',
    'eastern Mediterranean Sea': 'International Waters',
    'Gulf of America': 'United States',
    'Near the coast of Azerbaijan': 'Azerbaijan',
    'Near the coast of Oman': 'Oman',
    'Albania': 'Albania',
    'Strait of Gibraltar': 'International Waters',
    '21 km NNE of Ta': 'Unknown',
    '19 km NNE of Ta': 'Unknown',
    '16 km NNE of Ta': 'Unknown',
    '20 km NNE of Ta': 'Unknown',
    '15 km NNE of Ta': 'Unknown',
    'northwestern Kashmir': 'India',
    'East of the Volcano Islands': 'Japan',
    'Tennessee-Virginia border region': 'United States',
    'Laccadive Sea': 'India',
    'Kansas': 'United States',
    'Pitcairn Islands region': 'United Kingdom',
    'Crozet Islands region': 'France',
})

In [53]:
df.alert.unique()

<StringArray>
[nan, 'green', 'yellow', 'orange', 'red']
Length: 5, dtype: str

In [54]:

df.drop_duplicates()

,id,time,updated,latitude,longitude,depth_km,mag,magType,place,status,...,code,title,year,month,day,day_of_week,depth_flag,mag_flag,origin,country
0,us7000rs0p,2026-01-25 22:02:10.618000+00:00,2026-01-26 01:55:14.040000+00:00,23.3940,143.4290,10.000,5.00,MB,"Volcano Islands, Japan region",reviewed,...,7000rs0p,"M 5.0 - Volcano Islands, Japan region",2026,1,25,Sunday,Shallow,Strong,Volcano Islands,Japan region
1,us7000rs0i,2026-01-25 20:29:01.866000+00:00,2026-01-25 20:46:45.040000+00:00,-8.6248,-74.6666,122.560,4.60,MB,"16 km NNE of Honoria, Peru",reviewed,...,7000rs0i,"M 4.6 - 16 km NNE of Honoria, Peru",2026,1,25,Sunday,Deep,Moderate/Minor,16 km NNE of Honoria,Peru
2,ak2026btoyfc,2026-01-25 19:51:55.287000+00:00,2026-01-25 20:23:58.827000+00:00,67.6520,-166.6220,5.500,3.80,ML,"77 km S of Point Hope, Alaska",reviewed,...,2026btoyfc,"M 3.8 - 77 km S of Point Hope, Alaska",2026,1,25,Sunday,Shallow,Moderate/Minor,77 km S of Point Hope,Alaska
3,us7000rs08,2026-01-25 19:24:40.117000+00:00,2026-01-25 19:40:39.040000+00:00,-31.4355,-71.5445,41.926,4.50,MWR,"41 km WNW of Illapel, Chile",reviewed,...,7000rs08,"M 4.5 - 41 km WNW of Illapel, Chile",2026,1,25,Sunday,Shallow,Moderate/Minor,41 km WNW of Illapel,Chile
4,us7000rs01,2026-01-25 17:56:53.285000+00:00,2026-01-25 18:18:13.040000+00:00,37.5901,21.4946,36.351,4.10,MB,"4 km S of Epitálio, Greece",reviewed,...,7000rs01,"M 4.1 - 4 km S of Epitálio, Greece",2026,1,25,Sunday,Shallow,Moderate/Minor,4 km S of Epitálio,Greece
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
103655,pr2021027002,2021-01-27 04:10:20.820000+00:00,2021-04-13 17:04:22.040000+00:00,19.3328,-67.2320,23.000,3.61,MD,"94 km N of San Antonio, Puerto Rico",reviewed,...,2021027002,"M 3.6 - 94 km N of San Antonio, Puerto Rico",2021,1,27,Wednesday,Shallow,Moderate/Minor,94 km N of San Antonio,Puerto Rico
103656,us7000d3nd,2021-01-27 04:08:27.072000+00:00,2021-04-13 17:04:15.040000+00:00,-61.8961,-55.3861,10.000,5.00,MB,South Shetland Islands,reviewed,...,7000d3nd,M 5.0 - South Shetland Islands,2021,1,27,Wednesday,Shallow,Strong,South Shetland Islands,NaN
103657,us7000d3kg,2021-01-27 03:13:22.948000+00:00,2021-04-13 17:04:13.040000+00:00,-10.5209,123.7781,10.000,4.90,MB,"43 km SSE of Kupang, Indonesia",reviewed,...,7000d3kg,"M 4.9 - 43 km SSE of Kupang, Indonesia",2021,1,27,Wednesday,Shallow,Moderate/Minor,43 km SSE of Kupang,Indonesia
103658,us6000deej,2021-01-27 02:52:29.712000+00:00,2021-04-13 17:05:44.040000+00:00,13.1762,92.5357,29.290,4.40,MB,"164 km N of Bamboo Flat, India",reviewed,...,6000deej,"M 4.4 - 164 km N of Bamboo Flat, India",2021,1,27,Wednesday,Shallow,Moderate/Minor,164 km N of Bamboo Flat,India
103659,us6000deei,2021-01-27 02:00:37.079000+00:00,2021-04-13 17:06:39.040000+00:00,-18.7130,65.2006,10.000,4.40,MB,"216 km ENE of Port Mathurin, Mauritius",reviewed,...,6000deei,"M 4.4 - 216 km ENE of Port Mathurin, Mauritius",2021,1,27,Wednesday,Shallow,Moderate/Minor,216 km ENE of Port Mathurin,Mauritius

In [55]:
df.id.nunique()

103660

In [58]:
!pip install mysqlclient

Collecting mysqlclient
  Downloading mysqlclient-2.2.7-cp312-cp312-win_amd64.whl.metadata (4.8 kB)
Downloading mysqlclient-2.2.7-cp312-cp312-win_amd64.whl (208 kB)
Installing collected packages: mysqlclient
Successfully installed mysqlclient-2.2.7

In [59]:
!pip install pymysql

Collecting pymysql
  Downloading pymysql-1.1.2-py3-none-any.whl.metadata (4.3 kB)
Downloading pymysql-1.1.2-py3-none-any.whl (45 kB)
Installing collected packages: pymysql
Successfully installed pymysql-1.1.2

In [63]:
import MySQLdb

try:
    print("Trying to connect to MySQL...")
    db = MySQLdb.connect(
        host="127.0.0.1",  # safer than localhost on Windows
        user="root",
        passwd="Sindhuravi@3",
        db="USGS",
        connect_timeout=5
    )
    print("✅ Connected successfully")

    # Optional: test a query
    cursor = db.cursor()
    cursor.execute("SHOW TABLES;")
    tables = cursor.fetchall()
    print("Tables in 'USGS' database:", tables)
    
except MySQLdb.Error as e:
    print("❌ Error connecting to MySQL:", e)

Trying to connect to MySQL...
✅ Connected successfully
Tables in 'USGS' database: (('earthquakes',),)

In [64]:
!pip install sqlalchemy

Collecting sqlalchemy
  Using cached sqlalchemy-2.0.46-cp312-cp312-win_amd64.whl.metadata (9.8 kB)
Collecting greenlet>=1 (from sqlalchemy)
  Using cached greenlet-3.3.1-cp312-cp312-win_amd64.whl.metadata (3.8 kB)
Collecting typing-extensions>=4.6.0 (from sqlalchemy)
  Downloading typing_extensions-4.15.0-py3-none-any.whl.metadata (3.3 kB)
Using cached sqlalchemy-2.0.46-cp312-cp312-win_amd64.whl (2.1 MB)
Using cached greenlet-3.3.1-cp312-cp312-win_amd64.whl (227 kB)
Downloading typing_extensions-4.15.0-py3-none-any.whl (44 kB)
Installing collected packages: typing-extensions, greenlet, sqlalchemy

   ------------- -------------------------- 1/3 [greenlet]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   -------------------------- ------------- 2/3 [sqlalchemy]
   ---------------------------------------- 3/3 [sqlalchemy]

Successfully installed greenlet-3.3.1 sqlalchemy-2.0.46 typing-extensions-4.15.0

In [75]:

from sqlalchemy import create_engine
engine = create_engine("mysql+pymysql://root:sindhuravi@localhost:3306/usgs")
conn_alchemy = engine.connect()
print("SQLAlchemy connection established!")

SQLAlchemy connection established!

In [76]:
cursor.execute("CREATE DATABASE IF NOT EXISTS usgs_db;")
print("MySQL database 'usgs_db' created successfully!")

MySQL database 'usgs_db' created successfully!

In [79]:
cursor.execute("USE usgs_db;")  # Select database
cursor.execute("""
    CREATE TABLE IF NOT EXISTS earthquakes (
    id VARCHAR(64) PRIMARY KEY,
    time DATETIME,
    updated DATETIME,
    latitude float,
    longitude float,
    depth_km float,
    mag float,
    magType VARCHAR(32),
    place VARCHAR(255),
    status VARCHAR(32),
    tsunami INT,
    sig INT,
    net VARCHAR(32),
    nst float,
    dmin float,
    rms float,
    gap float,
    magError float,
    depthError float,
    magNst float,
    locationSource VARCHAR(64),
    magSource VARCHAR(64),
    types TEXT,
    ids TEXT,
    sources TEXT,
    type VARCHAR(32),
    tz VARCHAR(32),
    felt float,
    cdi float,
    mmi float,
    alert VARCHAR(32),
    code VARCHAR(64),
    title VARCHAR(255),
    year INT,
    month INT,
    day INT,
    day_of_week VARCHAR(16),
    depth_flag VARCHAR(16),
    mag_flag VARCHAR(16),
    origin VARCHAR(255),
    country VARCHAR(128)
);
    """)
db.commit()
print("Table Earthquake created Successfully !")

Table Earthquake created Successfully !

In [81]:
df.to_sql("earthquakes", engine, if_exists="replace", index=False)
print("✅ Earthquake data stored successfully")

✅ Earthquake data stored successfully

In [82]:
df=df.drop(columns=['magError', 'depthError', 'magNst', 'locationSource', 'magSource']) # no records

In [83]:
df.columns

Index(['id', 'time', 'updated', 'latitude', 'longitude', 'depth_km', 'mag',
       'magType', 'place', 'status', 'tsunami', 'sig', 'net', 'nst', 'dmin',
       'rms', 'gap', 'types', 'ids', 'sources', 'type', 'tz', 'felt', 'cdi',
       'mmi', 'alert', 'code', 'title', 'year', 'month', 'day', 'day_of_week',
       'depth_flag', 'mag_flag', 'origin', 'country'],
      dtype='str')

In [84]:
df=df.drop(columns=['origin'])

In [86]:
columns_to_drop = [
    "depthError", "magError", "magNst", "locationSource", "magSource", "origin"
]

for col in columns_to_drop:
    cursor.execute(f"ALTER TABLE earthquakes DROP COLUMN {col};")

In [87]:
len(df[df['year'] == 2025])

22661

In [89]:
!pip install streamlit

Collecting streamlit
  Downloading streamlit-1.53.1-py3-none-any.whl.metadata (10 kB)
Collecting altair!=5.4.0,!=5.4.1,<7,>=4.0 (from streamlit)
  Downloading altair-6.0.0-py3-none-any.whl.metadata (11 kB)
Collecting blinker<2,>=1.5.0 (from streamlit)
  Using cached blinker-1.9.0-py3-none-any.whl.metadata (1.6 kB)
Collecting cachetools<7,>=5.5 (from streamlit)
  Downloading cachetools-6.2.5-py3-none-any.whl.metadata (5.6 kB)
Collecting click<9,>=7.0 (from streamlit)
  Downloading click-8.3.1-py3-none-any.whl.metadata (2.6 kB)
Requirement already satisfied: numpy<3,>=1.23 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from streamlit) (2.4.1)
Requirement already satisfied: packaging>=20 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from streamlit) (26.0)
Collecting pandas<3,>=1.4.0 (from streamlit)
  Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl.metadata (19 kB)
Collecting pillow<13,>=7.1.0 (from streamlit)
  Downloading pillow-12.1.0-cp312-cp312-win_amd64.whl.metadata (9.0 kB)
Collecting protobuf<7,>=3.20 (from streamlit)
  Downloading protobuf-6.33.4-cp310-abi3-win_amd64.whl.metadata (593 bytes)
Collecting pyarrow>=7.0 (from streamlit)
  Downloading pyarrow-23.0.0-cp312-cp312-win_amd64.whl.metadata (3.1 kB)
Requirement already satisfied: requests<3,>=2.27 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from streamlit) (2.32.5)
Collecting tenacity<10,>=8.1.0 (from streamlit)
  Downloading tenacity-9.1.2-py3-none-any.whl.metadata (1.2 kB)
Collecting toml<2,>=0.10.1 (from streamlit)
  Using cached toml-0.10.2-py2.py3-none-any.whl.metadata (7.1 kB)
Requirement already satisfied: typing-extensions<5,>=4.10.0 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from streamlit) (4.15.0)
Collecting watchdog<7,>=2.1.5 (from streamlit)
  Using cached watchdog-6.0.0-py3-none-win_amd64.whl.metadata (44 kB)
Collecting gitpython!=3.1.19,<4,>=3.0.7 (from streamlit)
  Downloading gitpython-3.1.46-py3-none-any.whl.metadata (13 kB)
Collecting pydeck<1,>=0.8.0b4 (from streamlit)
  Using cached pydeck-0.9.1-py2.py3-none-any.whl.metadata (4.1 kB)
Requirement already satisfied: tornado!=6.5.0,<7,>=6.0.3 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from streamlit) (6.5.4)
Collecting jinja2 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jinja2-3.1.6-py3-none-any.whl.metadata (2.9 kB)
Collecting jsonschema>=3.0 (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema-4.26.0-py3-none-any.whl.metadata (7.6 kB)
Requirement already satisfied: narwhals>=1.27.1 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit) (2.15.0)
Requirement already satisfied: colorama in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from click<9,>=7.0->streamlit) (0.4.6)
Collecting gitdb<5,>=4.0.1 (from gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached gitdb-4.0.12-py3-none-any.whl.metadata (1.2 kB)
Collecting smmap<6,>=3.0.1 (from gitdb<5,>=4.0.1->gitpython!=3.1.19,<4,>=3.0.7->streamlit)
  Using cached smmap-5.0.2-py3-none-any.whl.metadata (4.3 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from pandas<3,>=1.4.0->streamlit) (2025.3)
Requirement already satisfied: charset_normalizer<4,>=2 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2.6.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from requests<3,>=2.27->streamlit) (2026.1.4)
Collecting MarkupSafe>=2.0 (from jinja2->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl.metadata (2.8 kB)
Collecting attrs>=22.2.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading attrs-25.4.0-py3-none-any.whl.metadata (10 kB)
Collecting jsonschema-specifications>=2023.03.6 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl.metadata (2.9 kB)
Collecting referencing>=0.28.4 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading referencing-0.37.0-py3-none-any.whl.metadata (2.8 kB)
Collecting rpds-py>=0.25.0 (from jsonschema>=3.0->altair!=5.4.0,!=5.4.1,<7,>=4.0->streamlit)
  Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl.metadata (4.2 kB)
Requirement already satisfied: six>=1.5 in c:\users\jamun\guvi\global-seismic\.venv\lib\site-packages (from python-dateutil>=2.8.2->pandas<3,>=1.4.0->streamlit) (1.17.0)
Downloading streamlit-1.53.1-py3-none-any.whl (9.1 MB)
   ---------------------------------------- 0.0/9.1 MB ? eta -:--:--
   ---- ----------------------------------- 1.0/9.1 MB 6.3 MB/s eta 0:00:02
   ---------- ----------------------------- 2.4/9.1 MB 6.1 MB/s eta 0:00:02
   ---------------- ----------------------- 3.7/9.1 MB 6.1 MB/s eta 0:00:01
   --------------------- ------------------ 5.0/9.1 MB 6.2 MB/s eta 0:00:01
   --------------------------- ------------ 6.3/9.1 MB 6.1 MB/s eta 0:00:01
   --------------------------------- ------ 7.6/9.1 MB 6.1 MB/s eta 0:00:01
   ------------------------------------- -- 8.7/9.1 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 9.1/9.1 MB 6.0 MB/s  0:00:01
Downloading altair-6.0.0-py3-none-any.whl (795 kB)
   ---------------------------------------- 0.0/795.4 kB ? eta -:--:--
   ---------------------------------------- 795.4/795.4 kB 5.7 MB/s  0:00:00
Using cached blinker-1.9.0-py3-none-any.whl (8.5 kB)
Downloading cachetools-6.2.5-py3-none-any.whl (11 kB)
Downloading click-8.3.1-py3-none-any.whl (108 kB)
Downloading gitpython-3.1.46-py3-none-any.whl (208 kB)
Using cached gitdb-4.0.12-py3-none-any.whl (62 kB)
Downloading pandas-2.3.3-cp312-cp312-win_amd64.whl (11.0 MB)
   ---------------------------------------- 0.0/11.0 MB ? eta -:--:--
   ---- ----------------------------------- 1.3/11.0 MB 6.1 MB/s eta 0:00:02
   --------- ------------------------------ 2.6/11.0 MB 6.0 MB/s eta 0:00:02
   ------------- -------------------------- 3.7/11.0 MB 6.1 MB/s eta 0:00:02
   ------------------ --------------------- 5.0/11.0 MB 6.0 MB/s eta 0:00:01
   ---------------------- ----------------- 6.3/11.0 MB 6.1 MB/s eta 0:00:01
   --------------------------- ------------ 7.6/11.0 MB 6.1 MB/s eta 0:00:01
   ------------------------------- -------- 8.7/11.0 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 10.0/11.0 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 11.0/11.0 MB 5.9 MB/s  0:00:01
Downloading pillow-12.1.0-cp312-cp312-win_amd64.whl (7.0 MB)
   ---------------------------------------- 0.0/7.0 MB ? eta -:--:--
   ------- -------------------------------- 1.3/7.0 MB 6.1 MB/s eta 0:00:01
   -------------- ------------------------- 2.6/7.0 MB 6.0 MB/s eta 0:00:01
   ---------------------- ----------------- 3.9/7.0 MB 6.2 MB/s eta 0:00:01
   ---------------------------- ----------- 5.0/7.0 MB 6.2 MB/s eta 0:00:01
   ----------------------------------- ---- 6.3/7.0 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 7.0/7.0 MB 5.8 MB/s  0:00:01
Downloading protobuf-6.33.4-cp310-abi3-win_amd64.whl (436 kB)
Using cached pydeck-0.9.1-py2.py3-none-any.whl (6.9 MB)
Using cached smmap-5.0.2-py3-none-any.whl (24 kB)
Downloading tenacity-9.1.2-py3-none-any.whl (28 kB)
Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
Using cached watchdog-6.0.0-py3-none-win_amd64.whl (79 kB)
Downloading jinja2-3.1.6-py3-none-any.whl (134 kB)
Downloading jsonschema-4.26.0-py3-none-any.whl (90 kB)
Downloading attrs-25.4.0-py3-none-any.whl (67 kB)
Downloading jsonschema_specifications-2025.9.1-py3-none-any.whl (18 kB)
Downloading markupsafe-3.0.3-cp312-cp312-win_amd64.whl (15 kB)
Downloading pyarrow-23.0.0-cp312-cp312-win_amd64.whl (27.7 MB)
   ---------------------------------------- 0.0/27.7 MB ? eta -:--:--
   - -------------------------------------- 1.3/27.7 MB 6.1 MB/s eta 0:00:05
   --- ------------------------------------ 2.6/27.7 MB 6.3 MB/s eta 0:00:04
   ----- ---------------------------------- 3.7/27.7 MB 6.2 MB/s eta 0:00:04
   ------- -------------------------------- 5.0/27.7 MB 6.2 MB/s eta 0:00:04
   --------- ------------------------------ 6.3/27.7 MB 6.1 MB/s eta 0:00:04
   ---------- ----------------------------- 7.6/27.7 MB 6.2 MB/s eta 0:00:04
   ------------ --------------------------- 8.9/27.7 MB 6.2 MB/s eta 0:00:04
   -------------- ------------------------- 10.0/27.7 MB 6.1 MB/s eta 0:00:03
   ---------------- ----------------------- 11.3/27.7 MB 6.1 MB/s eta 0:00:03
   ------------------ --------------------- 12.6/27.7 MB 6.1 MB/s eta 0:00:03
   -------------------- ------------------- 13.9/27.7 MB 6.1 MB/s eta 0:00:03
   --------------------- ------------------ 15.2/27.7 MB 6.1 MB/s eta 0:00:03
   ----------------------- ---------------- 16.3/27.7 MB 6.1 MB/s eta 0:00:02
   ------------------------- -------------- 17.8/27.7 MB 6.1 MB/s eta 0:00:02
   --------------------------- ------------ 18.9/27.7 MB 6.1 MB/s eta 0:00:02
   ----------------------------- ---------- 20.2/27.7 MB 6.1 MB/s eta 0:00:02
   ------------------------------- -------- 21.5/27.7 MB 6.1 MB/s eta 0:00:02
   -------------------------------- ------- 22.8/27.7 MB 6.1 MB/s eta 0:00:01
   ---------------------------------- ----- 24.1/27.7 MB 6.1 MB/s eta 0:00:01
   ------------------------------------ --- 25.2/27.7 MB 6.1 MB/s eta 0:00:01
   -------------------------------------- - 26.7/27.7 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------  27.5/27.7 MB 6.1 MB/s eta 0:00:01
   ---------------------------------------- 27.7/27.7 MB 6.0 MB/s  0:00:04
Downloading referencing-0.37.0-py3-none-any.whl (26 kB)
Downloading rpds_py-0.30.0-cp312-cp312-win_amd64.whl (240 kB)
Installing collected packages: watchdog, toml, tenacity, smmap, rpds-py, pyarrow, protobuf, pillow, MarkupSafe, click, cachetools, blinker, attrs, referencing, pandas, jinja2, gitdb, pydeck, jsonschema-specifications, gitpython, jsonschema, altair, streamlit

   - --------------------------------------  1/23 [toml]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   -------- -------------------------------  5/23 [pyarrow]
   ---------- -----------------------------  6/23 [protobuf]
   ---------- -----------------------------  6/23 [protobuf]
   ---------- -----------------------------  6/23 [protobuf]
   ------------ ---------------------------  7/23 [pillow]
   ------------ ---------------------------  7/23 [pillow]
   ------------ ---------------------------  7/23 [pillow]
   ------------- --------------------------  8/23 [MarkupSafe]
   ----------------- ---------------------- 10/23 [cachetools]
   -------------------- ------------------- 12/23 [attrs]
  Attempting uninstall: pandas
   -------------------- ------------------- 12/23 [attrs]
    Found existing installation: pandas 3.0.0
   -------------------- ------------------- 12/23 [attrs]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
    Uninstalling pandas-3.0.0:
   ------------------------ --------------- 14/23 [pandas]
      Successfully uninstalled pandas-3.0.0
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   ------------------------ --------------- 14/23 [pandas]
   -------------------------- ------------- 15/23 [jinja2]
   --------------------------- ------------ 16/23 [gitdb]
   ----------------------------- ---------- 17/23 [pydeck]
   --------------------------------- ------ 19/23 [gitpython]
   ---------------------------------- ----- 20/23 [jsonschema]
   ------------------------------------ --- 21/23 [altair]
   ------------------------------------ --- 21/23 [altair]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   -------------------------------------- - 22/23 [streamlit]
   ---------------------------------------- 23/23 [streamlit]

Successfully installed MarkupSafe-3.0.3 altair-6.0.0 attrs-25.4.0 blinker-1.9.0 cachetools-6.2.5 click-8.3.1 gitdb-4.0.12 gitpython-3.1.46 jinja2-3.1.6 jsonschema-4.26.0 jsonschema-specifications-2025.9.1 pandas-2.3.3 pillow-12.1.0 protobuf-6.33.4 pyarrow-23.0.0 pydeck-0.9.1 referencing-0.37.0 rpds-py-0.30.0 smmap-5.0.2 streamlit-1.53.1 tenacity-9.1.2 toml-0.10.2 watchdog-6.0.0

  WARNING: Failed to remove contents in a temporary directory 'C:\Users\jamun\GUVI\Global-Seismic\.venv\Lib\site-packages\~andas'.
  You can safely remove it manually.

In [6]:
%%writefile app.py
import streamlit as st
import pandas as pd
import sqlalchemy
import plotly.express as px

# ---------------- DATABASE CONNECTION ---------------- #
engine = sqlalchemy.create_engine(
    "mysql+pymysql://root:sindhuravi@localhost:3306/usgs"
)

# ---------------- PAGE CONFIG ---------------- #
st.set_page_config(
    page_title="🌋 SeismoScope | Earthquake Intelligence Hub",
    page_icon="🌋",
    layout="wide",
    initial_sidebar_state="expanded"
)

# ---------------- CUSTOM SIDEBAR STYLE ---------------- #
st.markdown("""
    <style>
    /* Sidebar background */
    section[data-testid="stSidebar"] {
        background-color: #FFFFFF;  /* White background */
    }

    /* Sidebar title style */
    .sidebar-title {
        font-size: 22px;
        font-weight: bold;
        color: #FF4B4B;  /* You can keep red or change */
    }

    /* Sidebar text color (so text is visible on white) */
    .css-1d391kg {  /* sidebar content text */
        color: #000000;  /* black text */
    }
    </style>
""", unsafe_allow_html=True)

# ---------------- SIDEBAR BRANDING ---------------- #
st.sidebar.markdown("<p class='sidebar-title'>🌍 SeismoScope</p>", unsafe_allow_html=True)
st.sidebar.caption("Real-Time Seismic Intelligence Dashboard")

st.sidebar.markdown("---")

# ---------------- CREATIVE NAVIGATION ---------------- #
page = st.sidebar.radio(
    "🧭 Explore the Dashboard",
    [
        "🏠 Project Overview",
        "🗄️ Data Lab (SQL Explorer)",
        "📊 Seismic Insights",
        "👩‍💻 About the Creator"
    ]
)

st.sidebar.markdown("---")
st.sidebar.info("Powered by USGS Earthquake Data")


# -------------------------------- PAGE 1 --------------------------------
if page == "🏠 Project Overview":

    # Hero Section
    st.markdown("""
        <h1 style='text-align: center; color: #FF4B4B;'>
        🌋 SeismoScope: Global Earthquake Intelligence Platform
        </h1>
        <p style='text-align: center; font-size:18px;'>
        Turning Seismic Data into Actionable Insights
        </p>
    """, unsafe_allow_html=True)

    # Banner Image
    st.image("DashboardImage.png", width="stretch")

    st.markdown("---")

    # Project Description
    st.markdown("""
    ## 🌍 About This Project

    **SeismoScope** is an interactive seismic analytics dashboard built using 
    Python, SQL, and Streamlit to explore global earthquake activity over the last five years.

    The data is sourced from the 
    **United States Geological Survey (USGS)** and transformed into 
    meaningful insights using advanced SQL queries and visual analytics.

    This platform helps analyze:

    - 🌊 Tsunami-triggering events  
    - 🌎 Regional seismic intensity  
    - 📉 Depth vs Magnitude relationships  
    - 📈 Year-over-year earthquake trends  

    ---
    """)

    # Interactive Highlights Section
    st.subheader("⚡ Platform Capabilities")

    col1, col2, col3 = st.columns(3)

    col1.info("🗄️ **SQL Intelligence Lab**  \nRun advanced analytical queries on real earthquake data.")

    col2.success("📊 **Dynamic Visual Dashboards**  \nInteractive charts powered by Plotly.")

    col3.warning("🌍 **Geospatial Mapping**  \nVisualize global earthquake distribution in real-time.")

    st.markdown("---")

    # Tech Stack Section
    st.subheader("🛠️ Technology Stack")

    tech1, tech2, tech3, tech4 = st.columns(4)

    tech1.metric("Language", "Python 🐍")
    tech2.metric("Database", "MySQL 🗄️")
    tech3.metric("Framework", "Streamlit 🚀")
    tech4.metric("Visualization", "Plotly 📊")

    st.markdown("---")

    st.caption("📌 Database Used: `usgs_db` | Designed for Data-Driven Decision Making")

# -------------------------------- PAGE 2 --------------------------------
elif page == "🗄️ Data Lab (SQL Explorer)":

    st.markdown("""
    <h1 style='color:#FF4B4B;'>🧪 Seismic Intelligence Lab</h1>
    <p style='font-size:17px;'>Explore advanced earthquake analytics powered by SQL.</p>
    """, unsafe_allow_html=True)

    st.markdown("---")

    # Categorized Query Selection
    category = st.selectbox(
        "🔎 Choose Analysis Category",
        ["🌋 Magnitude Analysis",
         "🌊 Tsunami & Alerts",
         "🌍 Geographic Insights",
         "📈 Temporal Trends"]
    )

    query_options = {
        "🌋 Magnitude Analysis": {
            "Top 10 Strongest Earthquakes": """
                SELECT place, mag, depth_km, country
                FROM earthquakes
                WHERE type='earthquake'
                ORDER BY mag DESC LIMIT 10;
            """,
            "Top 10 Deepest Earthquakes": """
                SELECT place, depth_km, mag, country
                FROM earthquakes
                WHERE type='earthquake'
                ORDER BY depth_km DESC LIMIT 10;
            """
        },

        "🌊 Tsunami & Alerts": {
            "Tsunamis per Year": """
                SELECT year, COUNT(*) AS tsunami_count
                FROM earthquakes
                WHERE tsunami = 1
                GROUP BY year ORDER BY year;
            """,
            "Alert Level Distribution": """
                SELECT alert, COUNT(*) AS count
                FROM earthquakes
                WHERE alert IS NOT NULL
                GROUP BY alert ORDER BY count DESC;
            """
        },

        "🌍 Geographic Insights": {
            "Top Active Countries": """
                SELECT country, COUNT(*) AS total_quakes
                FROM earthquakes
                GROUP BY country
                ORDER BY total_quakes DESC LIMIT 10;
            """
        },

        "📈 Temporal Trends": {
            "Year with Most Earthquakes": """
                SELECT year, COUNT(*) AS count
                FROM earthquakes
                GROUP BY year
                ORDER BY count DESC LIMIT 1;
            """
        }
    }

    selected_query = st.selectbox(
        "📌 Select Analysis",
        list(query_options[category].keys())
    )

    query = query_options[category][selected_query]

    df = pd.read_sql(query, engine)

    st.markdown(f"### 📊 Results: {selected_query}")
    st.dataframe(df, width="stretch")

    st.success("✅ Query executed successfully.")

# -------------------------------- PAGE 3 --------------------------------
elif page == "📊 Seismic Insights":

    st.markdown("""
    <h1 style='color:#FF4B4B;'>🌍 Global Seismic Intelligence Dashboard</h1>
    <p style='font-size:17px;'>Real-time analytical overview of global earthquake activity.</p>
    """, unsafe_allow_html=True)

    st.markdown("---")

    base_query = """
        SELECT mag, depth_km, tsunami
        FROM earthquakes
        WHERE type='earthquake';
    """
    df = pd.read_sql(base_query, engine)

    # KPI Section
    st.subheader("⚡ Key Performance Indicators")

    k1, k2, k3, k4 = st.columns(4)

    k1.metric("Total Events", len(df))
    k2.metric("Average Magnitude", round(df['mag'].mean(), 2))
    k3.metric("Average Depth (km)", round(df['depth_km'].mean(), 2))
    k4.metric("Tsunami Events", df[df['tsunami'] == 1].shape[0])

    st.markdown("---")

    # Year Trend
    st.subheader("📈 Earthquake Trend Over Time")

    year_query = """
        SELECT year, COUNT(*) AS count
        FROM earthquakes
        WHERE type='earthquake'
        GROUP BY year ORDER BY year;
    """
    df_year = pd.read_sql(year_query, engine)

    st.line_chart(df_year, x="year", y="count", width="stretch")

    st.markdown("---")

    # Top Countries Bar Chart
    st.subheader("🌍 Top 10 Countries by Average Magnitude")

    mag_query = """
        SELECT country, AVG(mag) AS avg_mag
        FROM earthquakes
        GROUP BY country
        ORDER BY avg_mag DESC LIMIT 10;
    """
    df_mag = pd.read_sql(mag_query, engine)

    fig = px.bar(
        df_mag,
        x="avg_mag",
        y="country",
        orientation="h",
        color="avg_mag",
        color_continuous_scale="RdYlBu_r"
    )

    st.plotly_chart(fig, width="stretch")

    st.markdown("---")

    # 2025 Geo Visualization
    st.subheader("🌎 Global Earthquake Distribution (2025)")

    df_2025 = pd.read_sql("""
        SELECT latitude, longitude, mag, place
        FROM earthquakes
        WHERE type='earthquake' AND year=2025;
    """, engine)

    if df_2025.empty:
        st.warning("No earthquake data available for 2025.")
    else:
        geo_fig = px.scatter_geo(
            df_2025,
            lat="latitude",
            lon="longitude",
            color="mag",
            size="mag",
            projection="natural earth",
            hover_name="place",
            color_continuous_scale="RdYlBu_r"
        )
        st.plotly_chart(geo_fig, width="stretch")

# -------------------------------- PAGE 4 --------------------------------
elif page == "👩‍💻 About the Creator":

    st.markdown("""
    <h1 style='color:#FF4B4B;'>👩‍💻 About the Creator</h1>
    """, unsafe_allow_html=True)

    st.markdown("""
    ### 🌋 Project Developed By

    **Jamuna Murugavel**  
    Data Analyst | Python Developer | SQL Specialist  

    ---

    ### 🛠️ Core Skills
    - Python (Pandas, NumPy)
    - SQL (Advanced Queries & Window Functions)
    - Streamlit Dashboard Development
    - Data Visualization (Plotly)
    - Geospatial Analytics

    ---

    ### 🎯 Project Vision
    To transform raw seismic data into meaningful insights that help governments,
    engineers, and policy makers make informed disaster-management decisions.
    """)

    st.success("🚀 Thank you for exploring SeismoScope!")

Overwriting app.py